from typing import Generic, Protocol, TypeVar

T = TypeVar("T")


class GenericRepositoryProtocol(Protocol[T]):
    """Generic interface for repository operations (ISP & DIP compliant)."""
    async def get_by_id(self, entity_id: any) -> T | None: ...
    async def list_all(self, skip: int = 0, limit: int = 100) -> list[T]: ...
    async def create(self, entity: T) -> T: ...
    async def update(self, entity: T) -> T: ...
    async def delete(self, entity_id: any) -> bool: ...
