"""final

Revision ID: b50b3d3c002a
Revises: 64fa86bc55d9
Create Date: 2026-08-24 13:03:48.575894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50b3d3c002a'
down_revision: Union[str, None] = '64fa86bc55d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('opening_balance', sa.Float(precision=2), nullable=False),
    sa.CheckConstraint('opening_balance >= 0', name='check_balance_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(precision=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.CheckConstraint('tax >= 0 and  tax <= 28', name='check_tax'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('items')
    op.drop_table('customers')
    # ### end Alembic commands ###